// Regenerates the BountyEngine ABI for the web dApp and the worker from the
// Foundry build output, so they can never drift from src/BountyEngine.sol.
//
//   forge build && node script/gen-abi.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const artifact = JSON.parse(readFileSync(join(root, "out/BountyEngine.sol/BountyEngine.json"), "utf8"));
const abi = JSON.stringify(artifact.abi, null, 2);
const header = "// GENERATED by script/gen-abi.mjs from src/BountyEngine.sol — do not edit by hand.\n";

// --- web (typed) ---
const webPath = join(root, "web/src/lib/bountyAbi.ts");
const web = readFileSync(webPath, "utf8");
const marker = "export const MODE";
const webTail = web.slice(web.indexOf(marker));
writeFileSync(webPath, `${header}export const bountyEngineAbi = ${abi} as const;\n\n${webTail}`);

// --- worker (plain JS) ---
writeFileSync(
  join(root, "worker/abi.js"),
  `${header}export const BOUNTY_ENGINE_ABI = ${abi};\n\n` +
    "export const MODE = { Curated: 0, Verified: 1 };\n" +
    "export const STATUS = { Open: 0, Completed: 1, Cancelled: 2 };\n",
);

console.log(`ABI (${artifact.abi.length} entries) written to web/src/lib/bountyAbi.ts and worker/abi.js`);
