// Regenerates the BountyEngine ABI for the web dApp and the worker from the
// Foundry build output, so they can never drift from src/BountyEngine.sol.
//
//   forge build && node script/gen-abi.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const artifact = JSON.parse(readFileSync(join(root, "out/BountyEngine.sol/BountyEngine.json"), "utf8"));
const abi = JSON.stringify(artifact.abi, null, 2);
const header = "// GENERATED by script/gen-abi.mjs from src/BountyEngine.sol — do not edit by hand.\n";

// --- web (typed) ---
const webPath = join(root, "web/src/lib/bountyAbi.ts");
const web = readFileSync(webPath, "utf8");
const marker = "export const MODE";
const webTail = web.slice(web.indexOf(marker));
writeFileSync(webPath, `${header}export const bountyEngineAbi = ${abi} as const;\n\n${webTail}`);

// --- worker (plain JS) ---
writeFileSync(
  join(root, "worker/abi.js"),
  `${header}export const BOUNTY_ENGINE_ABI = ${abi};\n\n` +
    "export const MODE = { Curated: 0, Verified: 1 };\n" +
    "export const STATUS = { Open: 0, Completed: 1, Cancelled: 2 };\n",
);

console.log(`ABI (${artifact.abi.length} entries) written to web/src/lib/bountyAbi.ts and worker/abi.js`);

// --- worker extras: ERC-8183 evaluator/commerce ABIs + the reference agent's
// popcount implementation (compiled without CBOR metadata, so it passes
// TestVectorVerifier's purity scan). ---
const art = (p) => JSON.parse(readFileSync(join(root, "out", p), "utf8"));
const evaluator = art("VerifierEvaluator.sol/VerifierEvaluator.json");
const commerce = art("AgenticCommerce.sol/AgenticCommerce.json");
const popcount = art("TestVectorVerifier.t.sol/PopcountFast.json");
writeFileSync(
  join(root, "worker/artifacts.js"),
  `${header}` +
    `export const EVALUATOR_ABI = ${JSON.stringify(evaluator.abi)};\n\n` +
    `export const COMMERCE_ABI = ${JSON.stringify(commerce.abi)};\n\n` +
    `/** Creation bytecode of a bit-parallel popcount (see test/TestVectorVerifier.t.sol:PopcountFast). */\n` +
    `export const POPCOUNT_FAST_BYTECODE = "${popcount.bytecode.object}";\n`,
);
console.log("worker/artifacts.js written (evaluator, commerce, popcount)");
